version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    target-branch: master
    schedule:
      interval: weekly
    assignees:
      - ChristophShyper
    groups:
      gha-all:
        patterns:
          - "*"

  - package-ecosystem: pip
    directory: "/"
    target-branch: master
    schedule:
      interval: weekly
    assignees:
      - ChristophShyper
    groups:
      pip-patch-minor:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
      pip-major:
        patterns:
          - "*"
        update-types:
          - major
